2023-10-31 17:04:41,879 INFO    MainThread:148469 [wandb_setup.py:_flush():76] Current SDK version is 0.15.12
2023-10-31 17:04:41,879 INFO    MainThread:148469 [wandb_setup.py:_flush():76] Configure stats pid to 148469
2023-10-31 17:04:41,879 INFO    MainThread:148469 [wandb_setup.py:_flush():76] Loading settings from /home/chenlequn/.config/wandb/settings
2023-10-31 17:04:41,879 INFO    MainThread:148469 [wandb_setup.py:_flush():76] Loading settings from /home/chenlequn/GitHub/LDED-FusionNet/code/wandb/settings
2023-10-31 17:04:41,879 INFO    MainThread:148469 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-10-31 17:04:41,879 INFO    MainThread:148469 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-10-31 17:04:41,879 INFO    MainThread:148469 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-10-31 17:04:41,879 INFO    MainThread:148469 [wandb_init.py:_log_setup():528] Logging user logs to /home/chenlequn/GitHub/LDED-FusionNet/code/wandb/run-20231031_170441-g6f4rpqv/logs/debug.log
2023-10-31 17:04:41,879 INFO    MainThread:148469 [wandb_init.py:_log_setup():529] Logging internal logs to /home/chenlequn/GitHub/LDED-FusionNet/code/wandb/run-20231031_170441-g6f4rpqv/logs/debug-internal.log
2023-10-31 17:04:41,880 INFO    MainThread:148469 [wandb_init.py:_jupyter_setup():474] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fa094fddb20>
2023-10-31 17:04:41,880 INFO    MainThread:148469 [wandb_init.py:init():568] calling init triggers
2023-10-31 17:04:41,880 INFO    MainThread:148469 [wandb_init.py:init():575] wandb.init called with sweep_config: {}
config: {}
2023-10-31 17:04:41,880 INFO    MainThread:148469 [wandb_init.py:init():618] starting backend
2023-10-31 17:04:41,880 INFO    MainThread:148469 [wandb_init.py:init():622] setting up manager
2023-10-31 17:04:41,881 INFO    MainThread:148469 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-10-31 17:04:41,882 INFO    MainThread:148469 [wandb_init.py:init():628] backend started and connected
2023-10-31 17:04:41,887 INFO    MainThread:148469 [wandb_run.py:_label_probe_notebook():1276] probe notebook
2023-10-31 17:04:41,893 INFO    MainThread:148469 [wandb_init.py:init():720] updated telemetry
2023-10-31 17:04:41,955 INFO    MainThread:148469 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2023-10-31 17:06:12,053 ERROR   MainThread:148469 [wandb_init.py:init():779] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-10-31 17:06:14,064 ERROR   MainThread:148469 [wandb_init.py:init():1188] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/home/chenlequn/anaconda3/envs/torch/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
  File "/home/chenlequn/anaconda3/envs/torch/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-10-31 17:07:09,150 INFO    MainThread:148469 [wandb_setup.py:_flush():76] Current SDK version is 0.15.12
2023-10-31 17:07:09,151 INFO    MainThread:148469 [wandb_setup.py:_flush():76] Configure stats pid to 148469
2023-10-31 17:07:09,151 INFO    MainThread:148469 [wandb_setup.py:_flush():76] Loading settings from /home/chenlequn/.config/wandb/settings
2023-10-31 17:07:09,151 INFO    MainThread:148469 [wandb_setup.py:_flush():76] Loading settings from /home/chenlequn/GitHub/LDED-FusionNet/code/wandb/settings
2023-10-31 17:07:09,151 INFO    MainThread:148469 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-10-31 17:07:09,151 INFO    MainThread:148469 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-10-31 17:07:09,151 INFO    MainThread:148469 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-10-31 17:07:09,151 INFO    MainThread:148469 [wandb_init.py:_log_setup():528] Logging user logs to /home/chenlequn/GitHub/LDED-FusionNet/code/wandb/run-20231031_170709-cmc3ljvg/logs/debug.log
2023-10-31 17:07:09,151 INFO    MainThread:148469 [wandb_init.py:_log_setup():529] Logging internal logs to /home/chenlequn/GitHub/LDED-FusionNet/code/wandb/run-20231031_170709-cmc3ljvg/logs/debug-internal.log
2023-10-31 17:07:09,151 INFO    MainThread:148469 [wandb_init.py:init():568] calling init triggers
2023-10-31 17:07:09,151 INFO    MainThread:148469 [wandb_init.py:init():575] wandb.init called with sweep_config: {}
config: {}
2023-10-31 17:07:09,151 INFO    MainThread:148469 [wandb_init.py:init():618] starting backend
2023-10-31 17:07:09,151 INFO    MainThread:148469 [wandb_init.py:init():622] setting up manager
2023-10-31 17:07:09,153 INFO    MainThread:148469 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-10-31 17:07:09,153 INFO    MainThread:148469 [wandb_init.py:init():628] backend started and connected
2023-10-31 17:07:09,161 INFO    MainThread:148469 [wandb_run.py:_label_probe_notebook():1276] probe notebook
2023-10-31 17:07:09,161 INFO    MainThread:148469 [wandb_init.py:init():720] updated telemetry
2023-10-31 17:07:09,233 INFO    MainThread:148469 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2023-10-31 17:08:39,328 ERROR   MainThread:148469 [wandb_init.py:init():779] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-10-31 17:08:41,338 ERROR   MainThread:148469 [wandb_init.py:init():1188] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/home/chenlequn/anaconda3/envs/torch/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
  File "/home/chenlequn/anaconda3/envs/torch/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
